# MySQL properties
spring.datasource.url=jdbc:mysql://localhost:3306/springrest?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=k2775G901Td9
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# HTTP: PATCH, DELETE, UPDATE
spring.mvc.hiddenmethod.filter.enabled=true

# Connection pool settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
